#!/usr/bin/env sh
#
# Here we source all files in the /shell directory.
#

local shellfilesdir=$DOTFILES_ROOT/shell
# set shellfilesdir $DOTFILES_ROOT/shell

source $shellfilesdir/base/aliases
# source $shellfilesdir/base/functions

source $shellfilesdir/dev/aliases
# source $shellfilesdir/dev/functions

source $shellfilesdir/ncl/aliases
# source $shellfilesdir/ncl/functions

## Setup dir_colors
# TODO May need different files for Mac.
local dir_colors_path=$DOTFILES_ROOT/shell/base/dir_colors

if [ "$TERM" != "dumb" ] && [ -f $dir_colors_path ]; then
  eval "$(dircolors $dir_colors_path)"
  # Might need this on Mac:
  # eval "$(dircolors -b $dir_colors_path)"
fi