#!/usr/bin/env sh
#
# Here we source all files in the /shell directory.
#

local shellfilesdir=$DOTFILES_ROOT/shell

source $shellfilesdir/base/aliases
# source $shellfilesdir/base/functions

source $shellfilesdir/dev/aliases
# source $shellfilesdir/dev/functions

source $shellfilesdir/ncl/aliases
# source $shellfilesdir/ncl/functions

## Setup dir_colors
# colored highlighting is awesome
local dir_colors_path=$DOTFILES_ROOT/shell/base/dir_colors

if [ "$TERM" != "dumb" ] && [ -x $dir_colors_path ]; then
  eval "$(dircolors $dir_colors_path)"
  # eval "$(dircolors -b $dir_colors_path)"
  echo "HERE"
  alias ls='ls --color=auto'
  #alias dir='ls --color=auto --format=vertical'
  #alias vdir='ls --color=auto --format=long'

  alias grep='grep --color=auto'
  alias fgrep='fgrep --color=auto'
  alias egrep='egrep --color=auto'
fi